load("//learning/gemini/agents/skill_rules:skills.bzl", "agent_skill")

package(default_visibility = ["//learning/gemini/agents/skills:__subpackages__"])

agent_skill(
    name = "gke_ai_troubleshooting_tpu_connection_failure_vbar_oom",
    srcs = ["SKILL.md"],
)
